config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  get 'dashboard', to: 'pages#dashboard'
  resources :bookings, only: [:update, :destroy]

  # resources :users, only: [:show]
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dogs do
    resources :bookings, except: [:index, :new]
    resources :reviews, only: [:create]
  end
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews
  # validation
  mount_uploader :photo, PhotoUploader
  validates :name, presence:true
  validates :description, presence:true
  validates :photo, presence:true
  validates :size, presence:true, inclusion: { in: %w(Small Medium Large)}
  validates :gender, presence:true, inclusion: { in: %w(Male Female)}
  validates :price, presence:true

   include PgSearch
   # pg_search_scope :search, :against => :name
   pg_search_scope :search_everything,
    against: [ :name, :breed, :size ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, except: [:new, :index, :create]

  def index

    @dogs = Dog.all.order(created_at: :desc)
    authorize @dogs
    if params[:search].present? && params[:location].present?
      search_dogs = Dog.search_everything(params[:search])
      users = User.near(params[:location], 20)
      location_dogs = []
      users.each do |u|
        u.dogs.each do |d|
          location_dogs << d
        end
      end
      @dogs = search_dogs & location_dogs

    elsif params[:location].present?
      users = User.near(params[:location], 20)
      location_dogs = []
      users.each do |u|
        u.dogs.each do |d|
          location_dogs << d
        end
      end
      @dogs = location_dogs

    elsif params[:search].present?
      @dogs = Dog.search_everything(params[:search])
    else
      @dogs = Dog.all
    end



    # @dogs = policy_scope(Dog).order(created_at: :desc)
    # @good_dogs = @dogs.select do |dog|
    #   !dog.user.latitude.nil? && !dog.user.longitude.nil?
    # end


    @markers = @dogs.map do |dog|
      {
        lat: dog.user.latitude,
        lng: dog.user.longitude,
        infoWindow: { content: render_to_string(partial: "shared/info_window", locals: { dog: dog }) }
      }
    end

  end


  def new
    @dog = Dog.new
    authorize @dog
  end

  def create
    @dog = Dog.new(dog_params)
    authorize @dog
    @dog.user = current_user
    if @dog.save
      redirect_to dog_path(@dog)
    else
      render "new"
    end
  end

  def edit
    authorize @dog
  end

  def update
    authorize @dog
    @dog.update(dog_params)
    if @dog.save
      redirect_to dogs_path
    else
      render "edit"
    end
  end

  def destroy
    authorize @dog
    @dog.delete
  end

  def show
    @booking = Booking.new

    @already_booked_start = @dog.bookings.map { |booking| booking.start_time.strftime("%Y-%m-%e ") }
    @already_booked_end = @dog.bookings.map { |booking| booking.end_time.strftime("%Y-%m-%e ") }
    @review = Review.new
  # @reviews = Review.all
  authorize @dog

  @markers =
  {
    lat: @dog.user.latitude,
    lng: @dog.user.longitude,

  }
  @new = average_rating(@dog)
end

private
def set_dog
 @dog = Dog.find(params[:id])
end

def dog_params
  params.require(:dog).permit(:name, :description, :breed, :gender, :photo, :size, :price)
end

def average_rating(dog)
  total = 0
  dog.reviews.each do |review|
    total += review.rating
  end
  if dog.reviews.count >= 1
    return total/ dog.reviews.count
  else
    return 0
  end
end
end

app/views/dogs/edit.html.erb
<div class="container">
  <!-- banner -->
<div class="small-banner" style="background-image: linear-gradient(-225deg, rgba(0,50,50,0.6) 0%, rgba(0,36,61,0.6) 50%),  url(<%= image_path "banner.jpg" %>);">
  <h1>Update Dog</h1>
</div>
<!-- simple form -->
<hr>
<%= simple_form_for @dog do |f|%>
<div class="col-xs-4 offset-md-4">
<%= f.input :name %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.input :breed %>
<%= f.input :size, collection: ["Small", "Medium", "Large"]%>
<%= f.input :gender, collection: ["Female", "Male"] %>
<%= f.submit %>
</div>
<hr>
<% end %>
</div>

app/views/dogs/index.html.erb
<!-- Below is the home banner -->
<!-- <div class="small-banner" style="background-image :linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%#= image_path "banner.jpg" %>);">
  <div>
    <h1 class="banner-h1">
      Le Woof
    </h1>
    <p class="banner-text">Connecting dog owners with local doggggg lovers</p>
    <a href="#dogs" class="button">
      Learn More
    </a>
  </div>
</div> -->
<!-- Above is the home banner -->

<!-- Below is the dogs cards container -->



<div class="container-index">
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <% @dogs.each do |dog| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card">
            <%= link_to dog, class: "card-link" do%>
            <% if dog.photo %>
              <% photo_url = cl_image_path dog.photo %>
            <% else %>
              <% photo_url = "url('https://goo.gl/images/GPguPA')" %>
            <% end %>
            <div class="card-photo" style="background-image: url('<%= photo_url %>');">

            </div>
            <div class="card-name">
              <h3><%= dog.name.capitalize %></h3>
              <p> Price p/h: $<%= dog.price %></p>
            </div>
            <div class="card-info">
              <p><%=h truncate(dog.description, length: 200) %></p>
            </div>
            <div class="card-date">
              <p>Added on: <%= Date.today %></p>
            </div>
            <%end%>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-3">
      <div class="map-woof">
        <div
          id="map"
          style="width:95%;
          height: 700px;"
          data-markers="<%= @markers.to_json %>"
        ></div>
      </div>
    </div>
  </div>
</div>

<!-- Above is the dogs cards container -->

app/views/dogs/new.html.erb
<div class="container">
  <!-- banner -->
<div class="small-banner" style="background-image: linear-gradient(-225deg, rgba(0,50,50,0.6) 0%, rgba(0,36,61,0.6) 50%),  url(<%= image_path "banner.jpg" %>);">
  <h1>New Dog</h1>
</div>
<!-- simple form -->
<hr>
<%= simple_form_for @dog do |f|%>
<div class="col-xs-4 offset-md-4">
<%= f.input :name %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.input :breed %>
<%= f.input :size, collection: ["Small", "Medium", "Large"]%>
<%= f.input :gender, collection: ["Female", "Male"] %>
<%= f.submit %>
</div>

<% end %>
</div>

app/views/dogs/search.html.erb
<!DOCTYPE html>


<h1>My First Google Map</h1>

<div id="map" style="width:400px;height:400px">

<div>
 <script src="https://maps.googleapis.com/maps/api/js?callback=myMap"></script>

app/views/dogs/search_results.html.erb
<!DOCTYPE html>


<h1>My First Google Map</h1>

<div id="map" style="width:400px;height:400px">

<div>
 <script src="https://maps.googleapis.com/maps/api/js?callback=myMap"></script>

app/views/dogs/show.html.erb
<div class="small-banner" style="background-image :linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path "banner.jpg" %>);">
  <div>
    <h1 class="banner-h1">
      Spend time with</h1>
      <h1 class="banner-h1">
       <%= @dog.name.capitalize %> </h1>
       <h1 class="banner-h1">the <%= @dog.breed.capitalize %>
    </h1>
  </div>
</div>






<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <h1><%= @dog.name.capitalize %></h1>
      <h3><em>Owner: <%= @dog.user.first_name.capitalize %></em> </h3>
      <div><%= cl_image_tag @dog.photo, height: 300, width: 350, crop: :fill%></div>
      <br>


      <h1><%= @dog.size.capitalize %> <%= @dog.breed.capitalize %> <% if @dog.gender == "male" %> <i class="fas fa-mars"></i>
        <% else %>
        <i class="fas fa-venus"></i>
        <%end%>
      </h1>



      <p class="description1"><%= @dog.description %></p>


      <% if policy(@dog).edit? %>
      <%= link_to 'Edit', edit_dog_path(@dog) %> |
      <% end %>

      <% if policy(@dog).destroy? %>
      <%= link_to 'Destroy', @dog, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>

      <h2>Average Rating</h2>
      <br>

      <h4>
        <% @new.times do %>
        <i class='fas fa-star bigger-star'></i>
        <% end %>
      </h4>
      <% if @dog.reviews.count >= 1 %>
      <br>
      <h2>Latest Reviews</h2>
      <% else %>
      <h4>No Reviews Yet</h4>
      <% end %>
      <br>
      <% @dog.reviews.last(3).each do |review|%>
      <h4><% review.rating.times do %>
        <i class='fas fa-star bigger-star'></i>
        <% end %>
      </h4>
        <p><%= review.content %></p>
        <% end %>
        <!-- </div> -->

        <!-- reviews list -->
        <!-- Reviews here -->
        <!-- <div class="col-md-4"> -->
        <div class="">
         <%= simple_form_for [@dog, @review], url: dog_reviews_path(@dog), method: :post do |f| %>
         <h3>Leave a Review for <%= @dog.name %></h3>

         <div>
          <i class="far fa-star bigger-star my-star" id = "star1"></i>
          <i class="far fa-star bigger-star my-star" id = "star2"></i>
          <i class="far fa-star bigger-star my-star" id = "star3"></i>
          <i class="far fa-star bigger-star my-star" id = "star4"></i>
          <i class="far fa-star bigger-star my-star" id = "star5"></i>
          <!-- </div> -->
          <%= f.input :rating, :as => :hidden %>
          <%= f.input :content %>
          <%= f.button :submit, "Review", class: "btn btn-success" %>
        </div>
        <% end %>
      </div>


    </div>
    <div class="booking-form col-xs-12 col-sm-6 col-md-4 pad-top">
      <h1> Book a walk with <%= @dog.name.capitalize %></h1>
      <%= simple_form_for [@dog, @booking] do |f| %>
      <h3>Price per hour: $<%= @dog.price %></h3>
      <%= f.input :start_time, as: :string, input_html: { class: "datepicker"} %>
      <%= f.input :end_time, as: :string, input_html: { class: "datepicker"} %>
      <%= f.input :details %>
      <%#= f.input :price, value: @dog.price, as: :hidden %>
      <%= f.button :submit, "Book Now", class: "btn btn-success"  %>
      <% end %>
    </div>
  </div>

  </div>
</div>



<!-- <div class="col-md-12 col-sm-6 col-xs-12"> -->
  <div
  id="map"
  style="width: 100%;
  height: 300px";
  class="map-woof"
  data-markers="<%= @markers.to_json %>"
  ></div>
  <!-- </div> -->
  <div id="bookingStart" data-dates="<%= @already_booked_start %>"></div>
  <div id="bookingEnd" data-dates="<%= @already_booked_end %>"></div>
  <script>

    const stars = Array.from(document.querySelectorAll(".my-star"));
    const div = document.querySelector(".rating");
  // console.log(stars)
  stars.forEach((star) => {
   star.addEventListener("click", function(event) {
    stars.forEach((star) => {
      star.classList.remove("fas")
    })

    starIndex = stars.indexOf(event.currentTarget);
    for (var i = 0; i <= starIndex; i++) {

      stars[i].classList.add("fas");
    }
      // console.log(starIndex)
      const ratingInput = document.getElementById('review_rating');
      ratingInput.value = starIndex + 1
    });
 });
</script>