config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  get 'dashboard', to: 'pages#dashboard'
  resources :bookings, only: [:update, :destroy]

  # resources :users, only: [:show]
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dogs do
    resources :bookings, except: [:index, :new]
    resources :reviews, only: [:create]
  end
end

app/views/pages/dashboard.html.erb
<div class="container dashboard">
  <div class="row">
    <div class="col-xs-12">

      <h2><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %>'s Bookings</h2>

      <% if @bookings.first.nil?%>
      <div class="row ">
       <div class="col-xs-12 text-center">
        <h3> You Currently Have No Bookings</h3>
        <h3> <%=link_to "+ Find a Dog", dogs_path %> </h3>
      </div>
    </div>
    <div class="row"></div>
    <% else %>

    <div class="row heading">
     <div class="col-xs-2">
       <h3> Booked With </h3>
     </div>
     <div class="col-xs-2">
       <h3> Start Time </h3>
     </div>
     <div class="col-xs-2">
       <h3> End Time</h3>
     </div>
     <div class="col-xs-1">
       <h3> Price</h3>
     </div>
     <div class="col-xs-2">
       <h3> Message</h3>
     </div>
     <div class="col-xs-1">
       <h3> Status</h3>
     </div>
      <div class="col-xs-2 text-center">
   <h3> Action</h3>
 </div>
   </div>
   <% @bookings.each do |booking| %>
   <div class="row">
     <div class="col-xs-2">
      <%=link_to booking.dog do%>
      <p><strong> <%=booking.dog.name.capitalize%> </strong></p>
      <%end%>
    </div>
    <div class="col-xs-2">
     <p> <%=booking.start_time.strftime("%e %b %Y %H:%M%p") %></p>
   </div>
   <div class="col-xs-2">
     <p> <%=booking.end_time.strftime("%e %b %Y %H:%M%p")%></p>
   </div>
   <div class="col-xs-1">
     <p> £<%=booking.price%></p>
   </div>
   <div class="col-xs-2">
     <p> <%=booking.details%></p>
   </div>
   <div class="col-xs-1">

     <p class="<%=booking.status%>" id="status-booking<%=booking.id%>">
      <span class="<%=booking.status%>" id="status-value<%=booking.id%>"><%=booking.status.capitalize%>
      </span> </p>

   </div>
    <div class="col-xs-1 text-center">
     <p> <%= link_to "Edit", dashboard_path %> </p>
   </div>
   <div class="col-xs-1 text-center">
     <p><%= link_to "Cancel", booking_path(booking, :status => "cancelled"), method: :patch,  remote: true%> </p>
   </div>
 </div>
 <%end%>
 <%end%>

 <hr>
</br>
<h2> My Dogs' Bookings </h2>
<% if @user.dogs.first.nil?%>
<div class="row ">
 <div class="col-xs-12 text-center">
  <h3> You Currently Have No Dogs</h3>
  <h3> <%=link_to "+ Add a Dog", new_dog_path %> </h3>
</div>
</div>
<div class="row"></div>
<% else %>
<div class="row heading">
 <div class="col-xs-1">
   <h3> Dog </h3>
 </div>
 <div class="col-xs-1">
   <h3>Client</h3>
 </div>
 <div class="col-xs-2">
   <h3> Start Time </h3>
 </div>
 <div class="col-xs-2">
   <h3> End Time</h3>
 </div>
 <div class="col-xs-1">
   <h3> Price</h3>
 </div>
 <div class="col-xs-2">
       <h3> Message</h3>
     </div>
 <div class="col-xs-1">
   <h3> Status</h3>
 </div>
 <div class="col-xs-2 text-center">
   <h3> Action</h3>
 </div>

</div>
<% @user.dogs.each do |dog| %>
<div class="row dog-booking">
 <div class="col-xs-2">
  <%=link_to dog do%>
  <p> <strong><%=dog.name.capitalize%> </strong></p>
  <%end%>
</div>
</div>
<% if dog.bookings.first.nil?%>
<div class="row ">
 <div class="col-xs-4">
  <p><%= dog.name %> currently has no bookings</p>

</div>
</div>
<div class="row"></div>
<% else %>
<% dog.bookings.each do |booking| %>
<div class="row">
 <div class="col-xs-1">
 </div>
 <div class="col-xs-1">
  <p> <%=booking.user.first_name.capitalize%> </p>
</div>
<div class="col-xs-2">
 <p> <%=booking.start_time.strftime("%e %b %Y %H:%M%p") %></p>
</div>
<div class="col-xs-2">
 <p> <%=booking.end_time.strftime("%e %b %Y %H:%M%p")%></p>
</div>
<div class="col-xs-1">
 <p> £<%=booking.price%></p>
</div>
<div class="col-xs-2">
     <p> <%=booking.details%></p>
   </div>
<div class="col-xs-1">
     <p id="status-booking<%=booking.id%>"> <span class="<%=booking.status%>" id="status-value<%=booking.id%>"> <%=booking.status.capitalize%> </span> </p>
   </div>
<div class="col-xs-1 text-center">
  <p><%= link_to "Accept", booking_path(booking, :status => "confirmed"), method: :patch, remote: true %>

</div>
<div class="col-xs-1 text-center">
  <p><%= link_to "Cancel", booking_path(booking, :status => "cancelled"), method: :patch,  remote: true%>

</div>
</div>
<%end%>
<br>
<%end%>
<%end%>
<%end%>
<hr>
</div>
</div>
</div>







</div>
</div>
</div>

app/views/pages/home.html.erb
<!-- Below is the home banner -->
<div class="home-banner" style="background-image :linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path "banner.jpg" %>);">
  <div>
    <h1 class="banner-h1">
      Le Woof
    </h1>
    <p class="banner-text"><span id = "banner-typed-text"></span></p>
    <a href="#more" class="button">
      Learn More
    </a>
  </div>
</div>
<!-- Above is the home banner -->

<!-- Below is the dogs cards container -->

<!-- <div class="your-class"> -->
  <!-- <div>your content</div> -->
  <!-- <div>your content</div> -->
  <!-- <div>your content</div> -->
<!-- </div> -->
<a name="dogs"></a>
<div class= "container">
<div class="cards-slick">

    <% @dogs.first(6).each do |dog| %>
    <div class="card">
      <%= link_to dog_path(dog), class: "card-link" do %>
        <% if dog.photo %>
          <% photo_url = cl_image_path dog.photo %>
        <% else %>
          <% photo_url = "url('https://goo.gl/images/GPguPA')" %>
        <% end %>
        <div class="card-photo" style="background-image: url('<%= photo_url %>');">

        </div>
        <div class="card-name">
          <div class='dog-name'><%= dog.name.capitalize %></div>
          <div class='dog-price' style="font-size: 13px; color:#827c7c; margin-top: 5px";>
            Price p/h: $<%= dog.price %>
          </div>
        </div>
        <div class="card-info">
          <p><%=h truncate(dog.description, length: 200) %></p>
        </div>
        <div class="card-date">
          <p>Added on: <%= Date.today %></p>
        </div>
      <% end %>
    </div>
  <% end %>

</div>
</div>
<div class="text-center">
<a href="/dogs" class="button">
      Show me more dogz
    </a></div>

<div id="bookingStart"></div>
<div id="bookingEnd"></div>

<div class="container">
  <a name="more"></a>
    <h1 class="text-center hiw-title">How it Works</h1>
    <hr style="width:250px; margin-bottom:30px; ">
  <div class="row">
    <div class="col-xs-12 col-sm-3 text-center">
      <%= image_tag "one.png", class: "hiw-image" %>
      <p class="hiw-card-top"><strong>Create a</strong> <em>free</em> <strong>profile</strong></p>
      <p class="hiw-card-description">Start searching for friendly local dogs or borrowers.</p>
    </div>
    <div class="col-xs-12 col-sm-3 text-center">
      <%= image_tag "two.png", class: "hiw-image" %>
      <p class="hiw-card-top"><strong>Make connections</strong></p>
      <p class="hiw-card-description">All Premium members are extensively vetted (pun intended).</p>
    </div>
    <div class="col-xs-12 col-sm-3 text-center">
      <%= image_tag "three.png", class: "hiw-image" %>
      <p class="hiw-card-top"><strong>Time to Meet</strong></p>
      <p class="hiw-card-description">Get to know other users and dogs face to face and build trust.</p>
    </div>
    <div class="col-xs-12 col-sm-3 text-center">
      <%= image_tag "four.png", class: "hiw-image" %>
      <p class="hiw-card-top"><strong>Share your love of dogs</strong></p>
      <p class="hiw-card-description">Have fun making new friends. Benefits for you and your dog.</p>
    </div>
  </div>

</div>

app/views/pages/update.js.erb
status = document.getElementById("status-booking<%=@booking.id%>");
status.InnerText = "<%=@booking.status%>"